import type {
  DirectorMannequinJoint,
  DirectorMannequinPoseCategory,
} from "@/lib/directorMannequin"

export type DirectorShortDramaHandShape =
  | "relaxed"
  | "straight"
  | "open"
  | "soft-fist"
  | "fist"
  | "point"
  | "waist"
  | "clasp"

export interface DirectorShortDramaPoseDefinition {
  id: string
  label: string
  category: DirectorMannequinPoseCategory
  description: string
  keywords: readonly string[]
  base: string
  hands?: Partial<Record<"left" | "right", DirectorShortDramaHandShape>>
  ground_contact?: "feet" | "left_knee" | "right_knee" | "pelvis"
  joints: Partial<Record<DirectorMannequinJoint, [number, number, number]>>
}

// These are single, editable performance beats for blocking and screenshots.
// They deliberately remain separate from time-based animation clips embedded
// in imported GLB files.
export const DIRECTOR_SHORT_DRAMA_POSE_DEFINITIONS = [
  {
    id: "arms-crossed",
    label: "抱臂",
    category: "基础站姿",
    description: "双肩前收、前臂在胸廓外侧交叠，手掌停在对侧上臂之外",
    keywords: ["抱胸", "怀疑", "冷淡", "等待"],
    base: "relaxed",
    hands: { left: "relaxed", right: "relaxed" },
    joints: {
      chest: [2, 0, 0], leftClavicle: [-3, 5, -3], rightClavicle: [-3, -5, 3],
      leftShoulder: [-37, -28, 0], rightShoulder: [-37, 28, 0],
      leftElbow: [-2, 20, 100], rightElbow: [-2, -20, -100],
      leftWrist: [8, -12, -18], rightWrist: [8, 12, 18],
    },
  },
  {
    id: "one-hand-hip",
    label: "单手叉腰",
    category: "基础站姿",
    description: "一手落在腰胯外侧，另一臂自然下垂，适合质问与等待",
    keywords: ["叉腰", "质问", "不耐烦"],
    base: "relaxed",
    hands: { right: "waist" },
    joints: {
      pelvis: [0, 3, 2], spine: [0, -2, -1], chest: [0, -4, 1],
      rightClavicle: [0, -2, 3], rightShoulder: [-6, -12, 50],
      rightElbow: [-12, 0, -106], rightWrist: [6, 10, 48],
      leftHip: [3, 0, -3], rightHip: [-5, 0, 4], rightKnee: [8, 0, 0],
    },
  },
  {
    id: "hands-front",
    label: "双手交握",
    category: "基础站姿",
    description: "双肘自然弯曲，双手在腹部前方交握且离开躯干表面",
    keywords: ["站姿", "礼貌", "接待", "双手放前"],
    base: "attention",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      leftShoulder: [-22, -6, -12], rightShoulder: [-22, 6, 12],
      leftElbow: [-58, 0, -32], rightElbow: [-58, 0, 32],
      leftWrist: [10, -8, -8], rightWrist: [10, 8, 8],
    },
  },
  {
    id: "hands-pockets",
    label: "双手插袋",
    category: "基础站姿",
    description: "肩臂放松，手掌落向裤袋开口并保持肘部在身体外侧",
    keywords: ["插兜", "休闲", "街头", "等待"],
    base: "relaxed",
    hands: { left: "soft-fist", right: "soft-fist" },
    joints: {
      leftShoulder: [-8, -8, -13], rightShoulder: [-8, 8, 13],
      leftElbow: [-34, 0, -28], rightElbow: [-34, 0, 28],
      leftWrist: [14, -8, -10], rightWrist: [14, 8, 10],
    },
  },
  {
    id: "lean-wall",
    label: "倚靠站立",
    category: "基础站姿",
    description: "骨盆侧移、肩线反向平衡，一腿放松形成自然倚靠感",
    keywords: ["靠墙", "倚靠", "放松", "等人"],
    base: "relaxed",
    joints: {
      pelvis: [0, 8, 7], spine: [0, -6, -4], spineMiddle: [0, -4, -2], chest: [0, -3, -2],
      neck: [0, 3, 1], head: [1, 5, 2],
      leftShoulder: [-6, 0, -12], rightShoulder: [-2, 0, 8],
      leftHip: [5, 0, -7], rightHip: [-12, 0, 7], rightKnee: [18, 0, 0],
      leftAnkle: [-2, 0, 0], rightAnkle: [6, 0, 0], rightToe: [-4, 0, 0],
    },
  },
  {
    id: "wait",
    label: "等候",
    category: "基础站姿",
    description: "重心落在后腿，双手在身前轻握，头部略向来人方向",
    keywords: ["等人", "候场", "站立", "耐心"],
    base: "hands-front",
    joints: {
      pelvis: [0, -4, 2], chest: [0, 4, 0], neck: [0, -3, 0], head: [0, -7, 0],
      leftHip: [3, 0, -3], rightHip: [-7, 0, 4], rightKnee: [10, 0, 0],
    },
  },
  {
    id: "beckon",
    label: "招手过来",
    category: "沟通交流",
    description: "一侧前臂抬起、掌心朝向自己，手指弯曲形成清晰招呼",
    keywords: ["过来", "召唤", "招呼", "勾手"],
    base: "explain",
    hands: { right: "clasp" },
    joints: {
      rightShoulder: [-42, -8, 54], rightElbow: [-72, 0, 54], rightWrist: [28, 18, -8],
      rightIndex1: [24, 0, 0], rightIndex2: [58, 0, 0], rightIndex3: [36, 0, 0],
    },
  },
  {
    id: "stop",
    label: "制止",
    category: "沟通交流",
    description: "单臂向前抬起，掌指张开形成明确停止手势",
    keywords: ["停", "拒绝", "别过来", "阻止"],
    base: "point",
    hands: { right: "open" },
    joints: {
      chest: [0, -6, 0], rightShoulder: [-22, -4, 72], rightElbow: [-12, 0, 8], rightWrist: [2, 12, -4],
    },
  },
  {
    id: "shrug",
    label: "摊手无奈",
    category: "沟通交流",
    description: "双肩上提、双肘外展、掌心摊开，表达不知道或无可奈何",
    keywords: ["摊手", "不知道", "无奈", "无所谓"],
    base: "open-arms",
    hands: { left: "open", right: "open" },
    joints: {
      leftClavicle: [4, 0, -7], rightClavicle: [4, 0, 7],
      leftShoulder: [-38, 0, -42], rightShoulder: [-38, 0, 42],
      leftElbow: [-54, 0, 36], rightElbow: [-54, 0, -36],
      leftWrist: [26, -12, 8], rightWrist: [26, 12, -8],
      neck: [2, 0, 0], head: [0, 7, 4],
    },
  },
  {
    id: "clap",
    label: "鼓掌",
    category: "沟通交流",
    description: "双臂在胸前合拢，掌面相对且手指伸直，适合单帧鼓掌节拍",
    keywords: ["拍手", "鼓掌", "赞同", "欢迎"],
    base: "attention",
    hands: { left: "straight", right: "straight" },
    joints: {
      leftShoulder: [-34, -8, -24], rightShoulder: [-34, 8, 24],
      leftElbow: [-64, 0, -38], rightElbow: [-64, 0, 38],
      leftWrist: [8, -8, -5], rightWrist: [8, 8, 5],
    },
  },
  {
    id: "greeting-bow",
    label: "点头问候",
    category: "沟通交流",
    description: "从髋部轻微前倾，颈部与头部保持自然点头角度",
    keywords: ["鞠躬", "问候", "致意", "礼貌"],
    base: "hands-front",
    joints: {
      pelvis: [7, 0, 0], spine: [8, 0, 0], spineMiddle: [5, 0, 0], chest: [3, 0, 0],
      neck: [-3, 0, 0], head: [8, 0, 0],
    },
  },
  {
    id: "apology-bow",
    label: "弯腰道歉",
    category: "沟通交流",
    description: "髋、腰和胸椎逐级前屈，双手在腹前交握完成正式道歉",
    keywords: ["道歉", "鞠躬", "认错", "赔礼"],
    base: "hands-front",
    joints: {
      pelvis: [12, 0, 0], spine: [18, 0, 0], spineMiddle: [12, 0, 0], chest: [8, 0, 0],
      neck: [-5, 0, 0], head: [12, 0, 0], leftHip: [6, 0, -2], rightHip: [6, 0, 2],
    },
  },
  {
    id: "whisper",
    label: "附耳低语",
    category: "沟通交流",
    description: "上身侧转靠近听者，一手在嘴侧形成遮挡但不压入面部",
    keywords: ["耳语", "说悄悄话", "秘密", "低声"],
    base: "explain",
    hands: { right: "open" },
    joints: {
      pelvis: [0, -8, 1], spine: [5, 8, -2], spineMiddle: [4, 8, 1], chest: [3, 10, 0],
      neck: [0, -8, 0], head: [4, -12, -4],
      rightShoulder: [-52, 26, 9], rightElbow: [-123, 24, -44], rightWrist: [6, 18, -18],
    },
  },
  {
    id: "listen",
    label: "侧耳倾听",
    category: "沟通交流",
    description: "头颈侧倾，一手停在耳后扩大倾听动作轮廓",
    keywords: ["听", "没听清", "侧耳", "询问"],
    base: "relaxed",
    hands: { right: "open" },
    joints: {
      chest: [0, -3, 1], neck: [0, 5, 8], head: [0, 8, 12],
      rightClavicle: [2, -2, 6], rightShoulder: [-52, 26, 9],
      rightElbow: [-123, 24, -44], rightWrist: [4, 18, -26],
    },
  },
  {
    id: "phone-call",
    label: "接听电话",
    category: "沟通交流",
    description: "右手持物姿态停在耳侧，手掌与手指离开脸颊表面",
    keywords: ["打电话", "接电话", "手机", "通话"],
    base: "one-hand-hip",
    hands: { right: "clasp" },
    joints: {
      rightClavicle: [2, -2, 6], rightShoulder: [-50, -4, 44],
      rightElbow: [-119, -21, 12], rightWrist: [4, 15, -20],
    },
  },
  {
    id: "selfie",
    label: "举机自拍",
    category: "沟通交流",
    description: "持机手臂向前上方伸出，头部转向镜头，另一手自然示意",
    keywords: ["自拍", "拍照", "手机", "直播"],
    base: "wave",
    hands: { right: "clasp", left: "open" },
    joints: {
      pelvis: [0, 4, 2], chest: [-2, -6, 0], neck: [0, 5, 0], head: [-2, 8, -3],
      rightShoulder: [-48, -16, 76], rightElbow: [-20, 0, 28], rightWrist: [8, 12, -5],
      leftShoulder: [-18, 0, -28], leftElbow: [-28, 0, 18],
    },
  },
  {
    id: "read-phone",
    label: "低头看手机",
    category: "沟通交流",
    description: "双手在胸腹前托住手机，头颈自然低下而不过度含胸",
    keywords: ["刷手机", "看消息", "发信息", "手机"],
    base: "hands-front",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      spine: [4, 0, 0], spineMiddle: [3, 0, 0], chest: [2, 0, 0], neck: [12, 0, 0], head: [16, 0, 0],
      leftShoulder: [-30, -6, -15], rightShoulder: [-30, 6, 15],
      leftElbow: [-54, 0, -22], rightElbow: [-54, 0, 22],
      leftWrist: [18, -5, -3], rightWrist: [18, 5, 3],
    },
  },
  {
    id: "handover",
    label: "递出物品",
    category: "沟通交流",
    description: "双手在身体前方向外托举，适合递文件、礼物或餐盘",
    keywords: ["递东西", "交付", "送礼", "文件"],
    base: "hands-front",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      pelvis: [3, 0, 0], spine: [4, 0, 0], chest: [2, 0, 0],
      leftShoulder: [-48, -5, -16], rightShoulder: [-48, 5, 16],
      leftElbow: [-32, 0, -12], rightElbow: [-32, 0, 12],
      leftWrist: [22, -4, -2], rightWrist: [22, 4, 2],
    },
  },
  {
    id: "handshake",
    label: "伸手握手",
    category: "沟通交流",
    description: "右臂向前下方伸出，掌指保持握手前的自然半开状态",
    keywords: ["握手", "合作", "认识", "见面"],
    base: "explain",
    hands: { right: "clasp" },
    joints: {
      pelvis: [2, -3, 0], spine: [3, 2, 0], chest: [2, 3, 0],
      rightShoulder: [-52, -8, 56], rightElbow: [-24, 0, 18], rightWrist: [10, 8, -5],
    },
  },
  {
    id: "hug",
    label: "张臂拥抱",
    category: "沟通交流",
    description: "双臂向前环抱但在胸前保留空间，手掌柔和张开",
    keywords: ["拥抱", "久别重逢", "安慰", "抱人"],
    base: "open-arms",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [3, 0, 0], spine: [4, 0, 0], chest: [3, 0, 0], neck: [-2, 0, 0],
      leftShoulder: [-48, -12, -54], rightShoulder: [-48, 12, 54],
      leftElbow: [-52, 0, 54], rightElbow: [-52, 0, -54],
      leftWrist: [12, -10, 8], rightWrist: [12, 10, -8],
    },
  },
  {
    id: "present",
    label: "双手展示",
    category: "沟通交流",
    description: "身体转向展示目标，双掌在腰胸高度共同托向一侧",
    keywords: ["展示", "介绍产品", "主持", "请看"],
    base: "open-arms",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [0, -5, 1], spine: [0, 4, -1], chest: [0, 7, 0], head: [0, -5, 0],
      leftShoulder: [-38, -12, -34], rightShoulder: [-30, -8, 48],
      leftElbow: [-48, 0, 34], rightElbow: [-42, 0, -28],
      leftWrist: [24, -12, 5], rightWrist: [24, -8, -5],
    },
  },
  {
    id: "surprise",
    label: "震惊",
    category: "情绪表演",
    description: "上身后缩、双手张开抬到胸侧，头部微后仰形成惊讶轮廓",
    keywords: ["吃惊", "震惊", "意外", "惊讶"],
    base: "open-arms",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [-4, 0, 0], spine: [-7, 0, 0], spineMiddle: [-5, 0, 0], chest: [-8, 0, 0], neck: [6, 0, 0], head: [-5, 0, 0],
      leftShoulder: [-28, -5, -62], rightShoulder: [-28, 5, 62],
      leftElbow: [-62, 0, 44], rightElbow: [-62, 0, -44],
      leftWrist: [18, -8, 4], rightWrist: [18, 8, -4],
    },
  },
  {
    id: "fear",
    label: "害怕后退",
    category: "情绪表演",
    description: "重心后移、肩臂抬起防护，双手位于面胸之前而不遮穿面部",
    keywords: ["恐惧", "害怕", "后退", "惊恐"],
    base: "surprise",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [-8, 2, 0], spine: [-12, -1, 0], chest: [-10, -2, 0], head: [-2, 8, 2],
      leftShoulder: [-18, -12, -78], rightShoulder: [-34, 10, 70],
      leftElbow: [-78, 0, 68], rightElbow: [-70, 0, -52],
      leftHip: [10, 0, -4], rightHip: [-18, 0, 4], rightKnee: [28, 0, 0],
    },
  },
  {
    id: "angry",
    label: "愤怒握拳",
    category: "情绪表演",
    description: "胸廓前压、双拳收紧停在身体外侧，形成克制发怒姿态",
    keywords: ["生气", "愤怒", "握拳", "对峙"],
    base: "attention",
    hands: { left: "fist", right: "fist" },
    joints: {
      pelvis: [-3, 0, 0], spine: [-5, 0, 0], chest: [-6, 0, 0], neck: [6, 0, 0], head: [4, 0, 0],
      leftClavicle: [2, 0, -4], rightClavicle: [2, 0, 4],
      leftShoulder: [-14, 0, -18], rightShoulder: [-14, 0, 18],
      leftElbow: [-42, 0, -18], rightElbow: [-42, 0, 18],
      leftWrist: [8, 0, 0], rightWrist: [8, 0, 0],
    },
  },
  {
    id: "argue",
    label: "激烈争辩",
    category: "情绪表演",
    description: "上身前倾，一手指向对方、另一手摊开，加强争执节奏",
    keywords: ["吵架", "争论", "指责", "冲突"],
    base: "point",
    hands: { left: "open", right: "point" },
    joints: {
      pelvis: [4, -5, 0], spine: [7, 4, 0], chest: [6, 7, 0], neck: [-3, -4, 0], head: [4, -7, 0],
      leftShoulder: [-34, 8, -38], leftElbow: [-48, 0, 28], leftWrist: [20, -8, 4],
      rightShoulder: [-26, -6, 88], rightElbow: [-8, 0, 4],
    },
  },
  {
    id: "cry",
    label: "掩面哭泣",
    category: "情绪表演",
    description: "肩背内收、头部低垂，双手停在面前并保持指掌在脸外",
    keywords: ["哭", "伤心", "崩溃", "掩面"],
    base: "hands-front",
    hands: { left: "open", right: "open" },
    joints: {
      spine: [10, 0, 0], spineMiddle: [8, 0, 0], chest: [8, 0, 0], neck: [12, 0, 0], head: [16, 0, 0],
      leftShoulder: [-52, -26, -9], rightShoulder: [-52, 26, 9],
      leftElbow: [-123, -24, 44], rightElbow: [-123, 24, -44],
      leftWrist: [6, -16, -20], rightWrist: [6, 16, 20],
    },
  },
  {
    id: "wipe-tears",
    label: "擦眼泪",
    category: "情绪表演",
    description: "一手轻靠眼下，另一臂垂落，头肩形成克制哭泣姿态",
    keywords: ["擦泪", "抽泣", "委屈", "难过"],
    base: "relaxed",
    hands: { right: "straight" },
    joints: {
      spine: [5, 0, 0], chest: [5, -3, 0], neck: [7, 2, 0], head: [10, 4, -3],
      rightShoulder: [-52, 26, 9], rightElbow: [-123, 24, -44], rightWrist: [3, 16, -26],
    },
  },
  {
    id: "laugh",
    label: "开怀大笑",
    category: "情绪表演",
    description: "胸廓打开、头部微仰，一手停在腹部并保持自然站姿",
    keywords: ["笑", "开心", "大笑", "喜悦"],
    base: "one-hand-hip",
    hands: { right: "open" },
    joints: {
      pelvis: [-2, 0, 1], spine: [-4, 0, -1], chest: [-7, 0, 0], neck: [4, 0, 0], head: [-8, 0, 0],
      rightShoulder: [-18, -8, 46], rightElbow: [-64, 0, -58], rightWrist: [18, 12, 24],
    },
  },
  {
    id: "shy",
    label: "害羞低头",
    category: "情绪表演",
    description: "骨盆侧移、肩线内收、双手轻握在身前并低头避开视线",
    keywords: ["害羞", "腼腆", "低头", "不好意思"],
    base: "hands-front",
    joints: {
      pelvis: [0, 5, 3], spine: [3, -3, -2], chest: [4, -4, -2], neck: [8, 4, 2], head: [12, 8, 4],
      leftHip: [2, 0, -4], rightHip: [-10, 0, 5], rightKnee: [14, 0, 0],
    },
  },
  {
    id: "plead",
    label: "恳求",
    category: "情绪表演",
    description: "双手在胸前交握，上身微前倾并抬头看向对方",
    keywords: ["求情", "拜托", "请求", "祈求"],
    base: "hands-front",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      pelvis: [4, 0, 0], spine: [6, 0, 0], chest: [4, 0, 0], neck: [-5, 0, 0], head: [-8, 0, 0],
      leftShoulder: [-34, -8, -24], rightShoulder: [-34, 8, 24],
      leftElbow: [-66, 0, -42], rightElbow: [-66, 0, 42],
      leftWrist: [6, -8, -6], rightWrist: [6, 8, 6],
    },
  },
  {
    id: "disappointed",
    label: "失落垂头",
    category: "情绪表演",
    description: "胸背轻度弯曲、头颈下垂、双臂松弛，表现失望和疲惫",
    keywords: ["失望", "沮丧", "垂头", "落寞"],
    base: "relaxed",
    joints: {
      pelvis: [4, 0, 0], spine: [8, 0, 0], spineMiddle: [7, 0, 0], chest: [6, 0, 0],
      neck: [12, 0, 0], head: [18, 0, 0],
      leftShoulder: [-8, 0, -5], rightShoulder: [-8, 0, 5],
      leftElbow: [-12, 0, 0], rightElbow: [-12, 0, 0],
    },
  },
  {
    id: "protect-head",
    label: "抱头防护",
    category: "情绪表演",
    description: "双前臂从头部两侧形成防护框架，掌指位于头颅外侧",
    keywords: ["抱头", "防护", "躲避", "害怕"],
    base: "fear",
    hands: { left: "open", right: "open" },
    joints: {
      spine: [10, 0, 0], chest: [8, 0, 0], neck: [12, 0, 0], head: [14, 0, 0],
      leftShoulder: [-8, -12, -110], rightShoulder: [-8, 12, 110],
      leftElbow: [-84, 0, 104], rightElbow: [-84, 0, -104],
      leftWrist: [4, -18, -34], rightWrist: [4, 18, 34],
    },
  },
  {
    id: "surrender",
    label: "举手投降",
    category: "情绪表演",
    description: "双臂高举、掌指完全张开，肩肘保留自然弧度",
    keywords: ["投降", "别开枪", "举手", "认输"],
    base: "celebrate",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [0, 0, 0], spine: [0, 0, 0], chest: [-2, 0, 0], head: [0, 0, 0],
      leftShoulder: [0, 0, -122], rightShoulder: [0, 0, 122],
      leftElbow: [-18, 0, 10], rightElbow: [-18, 0, -10],
      leftWrist: [2, 0, 0], rightWrist: [2, 0, 0],
    },
  },
  {
    id: "exhausted",
    label: "累到扶膝",
    category: "情绪表演",
    description: "髋部后移、上身前倾，双手落在膝上方并保持肘部外展",
    keywords: ["疲惫", "喘气", "扶膝", "累"],
    base: "crouch",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [16, 0, 0], spine: [18, 0, 0], spineMiddle: [12, 0, 0], chest: [8, 0, 0], neck: [-8, 0, 0], head: [6, 0, 0],
      leftShoulder: [-28, 0, -18], rightShoulder: [-28, 0, 18],
      leftElbow: [-44, 0, -18], rightElbow: [-44, 0, 18],
      leftHip: [-34, 0, -6], rightHip: [-34, 0, 6],
      leftKnee: [54, 0, 0], rightKnee: [54, 0, 0],
      leftAnkle: [-18, 0, 0], rightAnkle: [-18, 0, 0],
    },
  },
  {
    id: "cover-mouth",
    label: "捂嘴惊讶",
    category: "情绪表演",
    description: "一手停在嘴前留出安全间距，另一手自然下垂，适合吃惊反应",
    keywords: ["捂嘴", "惊讶", "秘密", "吃惊"],
    base: "surprise",
    hands: { right: "open" },
    joints: {
      leftShoulder: [-5, 0, -8], leftElbow: [-10, 0, 0],
      rightShoulder: [-52, 26, 9], rightElbow: [-123, 24, -44], rightWrist: [8, 15, -22],
    },
  },
  {
    id: "facepalm",
    label: "扶额无语",
    category: "情绪表演",
    description: "单手贴近额头但不穿入头部，头颈低下表达无语和懊恼",
    keywords: ["扶额", "无语", "懊恼", "头疼"],
    base: "disappointed",
    hands: { right: "open" },
    joints: {
      chest: [5, -3, 0], neck: [10, 3, 0], head: [14, 5, 0],
      rightShoulder: [-50, -4, 44], rightElbow: [-119, -21, 12], rightWrist: [4, 16, -30],
    },
  },
  {
    id: "headache",
    label: "头痛扶头",
    category: "情绪表演",
    description: "一手扶住太阳穴，躯干轻微侧弯并维持站立支撑",
    keywords: ["头疼", "眩晕", "不舒服", "扶头"],
    base: "relaxed",
    hands: { right: "open" },
    joints: {
      pelvis: [0, 3, 2], spine: [3, -2, -3], chest: [4, -3, -3], neck: [2, 4, 5], head: [5, 6, 7],
      rightShoulder: [-50, -4, 44], rightElbow: [-119, -21, 12], rightWrist: [3, 15, -27],
    },
  },
  {
    id: "stomachache",
    label: "捂腹疼痛",
    category: "情绪表演",
    description: "上身蜷缩、双手在腹部外侧交叠，膝部略屈保持平衡",
    keywords: ["肚子疼", "受伤", "腹痛", "生病"],
    base: "hands-front",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [8, 0, 0], spine: [12, 0, 0], spineMiddle: [9, 0, 0], chest: [8, 0, 0], neck: [8, 0, 0], head: [10, 0, 0],
      leftShoulder: [-18, -8, -18], rightShoulder: [-18, 8, 18],
      leftElbow: [-58, 0, -38], rightElbow: [-58, 0, 38],
      leftHip: [-12, 0, -3], rightHip: [-12, 0, 3], leftKnee: [24, 0, 0], rightKnee: [24, 0, 0],
    },
  },
  {
    id: "drink",
    label: "喝水",
    category: "日常生活",
    description: "持杯手停在嘴前，肘部自然下垂，头部略向杯口靠近",
    keywords: ["喝水", "喝茶", "喝咖啡", "杯子"],
    base: "relaxed",
    hands: { right: "clasp" },
    joints: {
      neck: [-2, 0, 0], head: [-5, 0, 0],
      rightShoulder: [-20, -8, 72], rightElbow: [-82, 0, 74], rightWrist: [12, 12, -18],
    },
  },
  {
    id: "eat",
    label: "进食",
    category: "日常生活",
    description: "一手持餐具靠近嘴部，另一手在腰前托住餐碗位置",
    keywords: ["吃饭", "餐具", "用餐", "吃东西"],
    base: "relaxed",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      spine: [2, 0, 0], head: [6, 0, 0],
      leftShoulder: [-24, -6, -18], leftElbow: [-58, 0, -34], leftWrist: [18, -6, -4],
      rightShoulder: [-18, -8, 78], rightElbow: [-78, 0, 78], rightWrist: [8, 12, -20],
    },
  },
  {
    id: "carry-box",
    label: "搬抱纸箱",
    category: "日常生活",
    description: "双臂在胸腹前形成环抱空间，腿部稳定承重且腰背保持中立",
    keywords: ["搬东西", "纸箱", "抱箱", "搬家"],
    base: "hands-front",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      pelvis: [2, 0, 0], spine: [2, 0, 0], chest: [-1, 0, 0],
      leftShoulder: [-42, -10, -38], rightShoulder: [-42, 10, 38],
      leftElbow: [-68, 0, 48], rightElbow: [-68, 0, -48],
      leftWrist: [10, -8, 5], rightWrist: [10, 8, -5],
      leftHip: [-6, 0, -3], rightHip: [-6, 0, 3], leftKnee: [14, 0, 0], rightKnee: [14, 0, 0],
    },
  },
  {
    id: "hold-baby",
    label: "怀抱婴儿",
    category: "日常生活",
    description: "双前臂在腹胸前形成稳定摇篮面，掌指柔和收拢",
    keywords: ["抱孩子", "抱婴儿", "哄娃", "怀抱"],
    base: "carry-box",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [0, 3, 1], chest: [-2, -4, 0], head: [8, 6, 0],
      leftShoulder: [-34, -12, -30], rightShoulder: [-38, 8, 34],
      leftElbow: [-78, 0, 54], rightElbow: [-70, 0, -48],
      leftWrist: [18, -10, 8], rightWrist: [18, 8, -8],
    },
  },
  {
    id: "sweep",
    label: "扫地",
    category: "日常生活",
    description: "双手上下错位握住长柄，上身转向清扫方向并屈膝发力",
    keywords: ["扫地", "清洁", "拖地", "家务"],
    base: "lunge",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      pelvis: [4, -8, 0], spine: [8, 7, 0], chest: [6, 8, 0], head: [4, -5, 0],
      leftShoulder: [-48, -10, -36], rightShoulder: [-28, -8, 48],
      leftElbow: [-34, 0, 12], rightElbow: [-62, 0, -42],
      leftWrist: [10, -6, 0], rightWrist: [12, 8, 0],
      leftHip: [-24, 0, -5], rightHip: [18, 0, 5], leftKnee: [38, 0, 0], rightKnee: [12, 0, 0],
    },
  },
  {
    id: "type",
    label: "键盘打字",
    category: "日常生活",
    description: "坐姿基础上双前臂平行前伸，双腕悬停在键盘上方",
    keywords: ["办公", "电脑", "打字", "键盘"],
    base: "sit",
    hands: { left: "relaxed", right: "relaxed" },
    joints: {
      spine: [5, 0, 0], chest: [2, 0, 0], head: [5, 0, 0],
      leftShoulder: [-38, -4, -18], rightShoulder: [-38, 4, 18],
      leftElbow: [-64, 0, -20], rightElbow: [-64, 0, 20],
      leftWrist: [16, -4, 0], rightWrist: [16, 4, 0],
    },
  },
  {
    id: "write",
    label: "伏案书写",
    category: "日常生活",
    description: "坐姿身体稍向桌面前倾，一手执笔、另一手平放辅助",
    keywords: ["写字", "签字", "做笔记", "办公"],
    base: "type",
    hands: { left: "open", right: "clasp" },
    joints: {
      pelvis: [10, 0, 0], spine: [10, 0, 0], spineMiddle: [6, 0, 0], chest: [4, -3, 0], neck: [4, 0, 0], head: [12, 4, 0],
      leftShoulder: [-40, -6, -22], leftElbow: [-56, 0, -14], leftWrist: [20, -5, 0],
      rightShoulder: [-46, 2, 20], rightElbow: [-70, 0, 26], rightWrist: [22, 5, -4],
    },
  },
  {
    id: "drive",
    label: "驾驶",
    category: "日常生活",
    description: "坐姿双手分置方向盘两侧，肩肘保持自然弯曲并目视前方",
    keywords: ["开车", "驾驶", "方向盘", "司机"],
    base: "sit",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      spine: [2, 0, 0], chest: [-2, 0, 0], head: [0, 0, 0],
      leftShoulder: [-42, -8, -32], rightShoulder: [-42, 8, 32],
      leftElbow: [-48, 0, -20], rightElbow: [-48, 0, 20],
      leftWrist: [8, -6, 0], rightWrist: [8, 6, 0],
    },
  },
  {
    id: "pick-up",
    label: "弯身拾取",
    category: "日常生活",
    description: "髋膝共同屈曲，一手伸向地面，支撑脚完整贴地",
    keywords: ["捡东西", "拾取", "拿地上物品", "弯腰"],
    base: "crouch",
    hands: { right: "clasp", left: "open" },
    joints: {
      pelvis: [4, -5, 0], spine: [16, 4, 0], spineMiddle: [12, 3, 0], chest: [8, 4, 0], neck: [-6, -2, 0], head: [10, -4, 0],
      leftShoulder: [-20, 0, -14], leftElbow: [-36, 0, -12],
      rightShoulder: [-54, -6, 42], rightElbow: [-24, 0, 12], rightWrist: [10, 4, 0],
      leftHip: [-54, 0, -6], rightHip: [-48, 0, 6], leftKnee: [92, 0, 0], rightKnee: [78, 0, 0],
      leftAnkle: [-38, 0, 0], rightAnkle: [-30, 0, 0],
    },
  },
  {
    id: "bend",
    label: "俯身查看",
    category: "日常生活",
    description: "从髋部前倾并保持背部延伸，双手自然垂向观察目标",
    keywords: ["弯腰", "查看", "俯身", "观察地面"],
    base: "relaxed",
    joints: {
      pelvis: [14, 0, 0], spine: [20, 0, 0], spineMiddle: [14, 0, 0], chest: [10, 0, 0], neck: [-8, 0, 0], head: [12, 0, 0],
      leftShoulder: [-12, 0, -8], rightShoulder: [-12, 0, 8],
      leftElbow: [-16, 0, 0], rightElbow: [-16, 0, 0],
      leftHip: [-8, 0, -2], rightHip: [-8, 0, 2], leftKnee: [18, 0, 0], rightKnee: [18, 0, 0],
    },
  },
  {
    id: "kneel",
    label: "单膝跪地",
    category: "日常生活",
    description: "前脚稳定、后膝落地，骨盆和脊柱保持直立并避免悬浮",
    keywords: ["下跪", "求婚", "单膝", "跪地"],
    base: "lunge",
    hands: { left: "clasp", right: "clasp" },
    ground_contact: "right_knee",
    joints: {
      pelvis: [-2, 0, 0], spine: [2, 0, 0], chest: [-2, 0, 0],
      leftShoulder: [-24, -5, -14], rightShoulder: [-24, 5, 14],
      leftElbow: [-58, 0, -30], rightElbow: [-58, 0, 30],
      leftWrist: [12, -5, -5], rightWrist: [12, 5, 5],
      leftHip: [-90, 0, -5], rightHip: [0, 0, 5],
      leftKnee: [90, 0, 0], rightKnee: [90, 0, 0],
      leftAnkle: [0, 0, 0], rightAnkle: [-18, 0, 0], leftToe: [0, 0, 0], rightToe: [18, 0, 0],
    },
  },
  {
    id: "sit-cross-legged",
    label: "盘腿坐地",
    category: "日常生活",
    description: "双髋外展、膝部弯曲，双手自然落在膝上并以身体最低点贴地",
    keywords: ["盘腿", "坐地", "冥想", "地面坐姿"],
    base: "sit",
    hands: { left: "open", right: "open" },
    ground_contact: "pelvis",
    joints: {
      pelvis: [4, 0, 0], spine: [1, 0, 0], chest: [-2, 0, 0],
      leftShoulder: [-18, -5, -18], rightShoulder: [-18, 5, 18],
      leftElbow: [-42, 0, -24], rightElbow: [-42, 0, 24],
      leftWrist: [18, -6, -4], rightWrist: [18, 6, 4],
      leftHip: [-70, -34, -55], rightHip: [-70, 34, 55],
      leftKnee: [145, 0, 0], rightKnee: [145, 0, 0],
      leftAnkle: [-14, -15, 0], rightAnkle: [-14, 15, 0], leftToe: [8, 0, 0], rightToe: [8, 0, 0],
    },
  },
  {
    id: "cook",
    label: "站立烹饪",
    category: "日常生活",
    description: "一手握锅柄位置，另一手前伸翻炒，身体略向灶台靠近",
    keywords: ["做饭", "炒菜", "厨房", "烹饪"],
    base: "relaxed",
    hands: { left: "clasp", right: "clasp" },
    joints: {
      pelvis: [2, -4, 0], spine: [4, 3, 0], chest: [3, 4, 0], head: [6, -4, 0],
      leftShoulder: [-38, -8, -26], leftElbow: [-52, 0, -22], leftWrist: [14, -6, 0],
      rightShoulder: [-52, -6, 48], rightElbow: [-36, 0, -18], rightWrist: [12, 6, 0],
      leftKnee: [8, 0, 0], rightKnee: [12, 0, 0],
    },
  },
  {
    id: "sneak",
    label: "弯腰潜行",
    category: "行走运动",
    description: "身体降低、步幅缩短、双臂收拢，形成谨慎潜行瞬间",
    keywords: ["潜行", "偷偷走", "蹑手蹑脚", "侦查"],
    base: "walk",
    hands: { left: "soft-fist", right: "soft-fist" },
    joints: {
      pelvis: [8, -5, 0], spine: [12, 4, 0], spineMiddle: [8, 3, 0], chest: [6, 4, 0], neck: [-6, -2, 0], head: [4, -4, 0],
      leftShoulder: [-28, 0, -18], rightShoulder: [-36, 0, 18],
      leftElbow: [-68, 0, 18], rightElbow: [-72, 0, -18],
      leftHip: [-38, 0, -5], rightHip: [18, 0, 5], leftKnee: [52, 0, 0], rightKnee: [28, 0, 0],
      leftAnkle: [-18, 0, 0], rightAnkle: [8, 0, 0],
    },
  },
  {
    id: "tiptoe",
    label: "踮脚探看",
    category: "行走运动",
    description: "双膝微屈、脚跟抬起，身体向前上方延伸并以手臂维持平衡",
    keywords: ["踮脚", "探头", "够高处", "小心走"],
    base: "relaxed",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [-4, 0, 0], spine: [-5, 0, 0], chest: [-4, 0, 0], neck: [5, 0, 0], head: [-4, 0, 0],
      leftShoulder: [-18, 0, -26], rightShoulder: [-18, 0, 26],
      leftElbow: [-24, 0, 12], rightElbow: [-24, 0, -12],
      leftHip: [-12, 0, -3], rightHip: [-12, 0, 3], leftKnee: [24, 0, 0], rightKnee: [24, 0, 0],
      leftAnkle: [32, 0, 0], rightAnkle: [32, 0, 0], leftToe: [-28, 0, 0], rightToe: [-28, 0, 0],
    },
  },
  {
    id: "stumble",
    label: "踉跄失衡",
    category: "行走运动",
    description: "骨盆偏移、躯干反向倾斜，双臂展开并用前后脚抢回平衡",
    keywords: ["踉跄", "绊倒", "失去平衡", "后退"],
    base: "walk",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [-10, 8, 8], spine: [-12, -6, -5], spineMiddle: [-8, -4, -3], chest: [-8, -5, -3], neck: [10, 4, 2], head: [2, 7, 3],
      leftShoulder: [-24, 4, -74], rightShoulder: [-14, -4, 82],
      leftElbow: [-28, 0, 24], rightElbow: [-34, 0, -28],
      leftHip: [-42, 0, -8], rightHip: [32, 0, 8], leftKnee: [66, 0, 0], rightKnee: [18, 0, 0],
      leftAnkle: [-16, 0, 0], rightAnkle: [12, 0, 0],
    },
  },
  {
    id: "fall-back",
    label: "跌坐后仰",
    category: "冲突动作",
    description: "身体向后失衡、双手撑向两侧、双腿屈曲，以身体最低点落地",
    keywords: ["摔倒", "跌倒", "跌坐", "被推倒"],
    base: "sit",
    hands: { left: "open", right: "open" },
    ground_contact: "pelvis",
    joints: {
      pelvis: [-8, 0, 0], spine: [-14, 0, 0], spineMiddle: [-10, 0, 0], chest: [-8, 0, 0], neck: [10, 0, 0], head: [5, 0, 0],
      leftShoulder: [38, -8, -34], rightShoulder: [38, 8, 34],
      leftElbow: [-34, 0, -18], rightElbow: [-34, 0, 18],
      leftHip: [-70, 0, -12], rightHip: [-64, 0, 12], leftKnee: [145, 0, 0], rightKnee: [140, 0, 0],
      leftAnkle: [-18, 0, 0], rightAnkle: [-14, 0, 0],
    },
  },
  {
    id: "punch",
    label: "直拳",
    category: "冲突动作",
    description: "后脚蹬地、髋胸同向转动，一拳前伸、另一拳保护下颌",
    keywords: ["打拳", "出拳", "格斗", "打架"],
    base: "lunge",
    hands: { left: "fist", right: "fist" },
    joints: {
      pelvis: [-5, -12, 0], spine: [-4, 10, 0], chest: [-3, 14, 0], neck: [4, -8, 0], head: [1, -8, 0],
      leftShoulder: [-58, -8, -74], leftElbow: [-8, 0, 6], leftWrist: [4, 0, 0],
      rightShoulder: [-28, 10, 68], rightElbow: [-86, 0, -72], rightWrist: [8, 0, 0],
      leftHip: [-34, 0, -6], rightHip: [30, 0, 6], leftKnee: [46, 0, 0], rightKnee: [12, 0, 0],
    },
  },
  {
    id: "kick",
    label: "前踢",
    category: "冲突动作",
    description: "支撑腿稳定，踢腿侧髋膝前伸，双拳在胸前保持防护",
    keywords: ["踢腿", "打斗", "格斗", "前踢"],
    base: "high-step",
    hands: { left: "fist", right: "fist" },
    joints: {
      pelvis: [-6, 0, 1], spine: [-7, 0, -1], chest: [-5, 0, 0],
      leftShoulder: [-32, -6, -28], rightShoulder: [-36, 6, 28],
      leftElbow: [-76, 0, -34], rightElbow: [-76, 0, 34],
      leftHip: [-92, 0, -4], rightHip: [8, 0, 4], leftKnee: [18, 0, 0], rightKnee: [8, 0, 0],
      leftAnkle: [-6, 0, 0], rightAnkle: [2, 0, 0], leftToe: [4, 0, 0], rightToe: [0, 0, 0],
    },
  },
  {
    id: "block",
    label: "抬臂格挡",
    category: "冲突动作",
    description: "双前臂在头胸前形成交叉防线，手掌握拳且不压入面部",
    keywords: ["格挡", "防御", "挡住", "打架"],
    base: "angry",
    hands: { left: "fist", right: "fist" },
    joints: {
      pelvis: [-4, 0, 0], spine: [-5, 0, 0], chest: [-4, 0, 0],
      leftShoulder: [-24, -10, -94], rightShoulder: [-24, 10, 94],
      leftElbow: [-76, 0, 72], rightElbow: [-76, 0, -72],
      leftWrist: [8, -10, -14], rightWrist: [8, 10, 14],
      leftHip: [-18, 0, -4], rightHip: [12, 0, 4], leftKnee: [30, 0, 0], rightKnee: [18, 0, 0],
    },
  },
  {
    id: "push",
    label: "双手推开",
    category: "冲突动作",
    description: "身体前倾、双臂向前发力，掌指张开并由前后腿提供支撑",
    keywords: ["推人", "推门", "推开", "冲突"],
    base: "lunge",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [5, 0, 0], spine: [8, 0, 0], chest: [5, 0, 0], neck: [-4, 0, 0],
      leftShoulder: [-62, -6, -22], rightShoulder: [-62, 6, 22],
      leftElbow: [-12, 0, -4], rightElbow: [-12, 0, 4],
      leftWrist: [2, -8, 0], rightWrist: [2, 8, 0],
      leftHip: [-36, 0, -5], rightHip: [28, 0, 5], leftKnee: [48, 0, 0], rightKnee: [8, 0, 0],
    },
  },
  {
    id: "dodge",
    label: "侧身闪避",
    category: "冲突动作",
    description: "骨盆与胸廓快速侧倾旋转，双臂护住头胸并保持脚下支撑",
    keywords: ["躲闪", "闪避", "侧身", "避开"],
    base: "fear",
    hands: { left: "soft-fist", right: "soft-fist" },
    joints: {
      pelvis: [-6, 14, 10], spine: [-8, -10, -8], spineMiddle: [-6, -8, -6], chest: [-5, -9, -6], neck: [7, 8, 4], head: [2, 12, 5],
      leftShoulder: [-30, -8, -76], rightShoulder: [-42, 12, 58],
      leftElbow: [-72, 0, 58], rightElbow: [-78, 0, -48],
      leftHip: [-28, 0, -8], rightHip: [18, 0, 8], leftKnee: [48, 0, 0], rightKnee: [26, 0, 0],
    },
  },
  {
    id: "slap",
    label: "挥手掌掴",
    category: "冲突动作",
    description: "髋胸带动单臂横向挥出，手掌伸展、另一臂留在身体外侧平衡",
    keywords: ["扇耳光", "掌掴", "挥手", "冲突"],
    base: "lunge",
    hands: { left: "open", right: "open" },
    joints: {
      pelvis: [-2, -14, 0], spine: [-2, 12, 0], chest: [-1, 18, 0], neck: [2, -10, 0], head: [0, -12, 0],
      leftShoulder: [-34, 6, -84], leftElbow: [-18, 0, 8], leftWrist: [6, -8, 0],
      rightShoulder: [-24, -6, 34], rightElbow: [-52, 0, -32],
      leftHip: [-28, 0, -5], rightHip: [22, 0, 5], leftKnee: [38, 0, 0], rightKnee: [12, 0, 0],
    },
  },
] as const satisfies readonly DirectorShortDramaPoseDefinition[]

export type DirectorShortDramaPoseId = typeof DIRECTOR_SHORT_DRAMA_POSE_DEFINITIONS[number]["id"]
