import { DIRECTOR_UNIVERSAL_HUMAN_MOTIONS } from "@/lib/directorHumanMotions"
import type { DirectorMannequinJoint } from "@/lib/directorMannequin"

export const DIRECTOR_UNIVERSAL_MANNEQUIN = {
  id: "bundled:mesh2motion:universal-human-actions",
  name: "通用动作白模",
  modelFile: "human-base.glb",
  alternateModelFile: "human-female.glb",
  animationFiles: ["human-base-animations.glb", "human-addon-animations.glb"],
  license: "CC0 1.0 · Mesh2Motion / Quaternius",
  stats: {
    nodeCount: 68,
    meshCount: 1,
    materialCount: 1,
    boneCount: 66,
    animationCount: DIRECTOR_UNIVERSAL_HUMAN_MOTIONS.length,
  },
  motions: DIRECTOR_UNIVERSAL_HUMAN_MOTIONS,
} as const

/**
 * The bundled mannequin files are project assets, so their exact skeleton is
 * maintained here rather than re-detected in every browser session.
 */
export const DIRECTOR_UNIVERSAL_MANNEQUIN_JOINT_MAP: Partial<Record<DirectorMannequinJoint, string>> = {
  pelvis: "pelvis",
  spine: "spine_01",
  spineMiddle: "spine_02",
  chest: "spine_03",
  neck: "neck_01",
  head: "head",
  leftClavicle: "clavicle_l",
  leftShoulder: "upperarm_l",
  leftElbow: "lowerarm_l",
  leftWrist: "hand_l",
  leftThumb1: "thumb_01_l",
  leftThumb2: "thumb_02_l",
  leftThumb3: "thumb_03_l",
  leftIndex1: "index_01_l",
  leftIndex2: "index_02_l",
  leftIndex3: "index_03_l",
  leftMiddle1: "middle_01_l",
  leftMiddle2: "middle_02_l",
  leftMiddle3: "middle_03_l",
  leftRing1: "ring_01_l",
  leftRing2: "ring_02_l",
  leftRing3: "ring_03_l",
  leftPinky1: "pinky_01_l",
  leftPinky2: "pinky_02_l",
  leftPinky3: "pinky_03_l",
  rightClavicle: "clavicle_r",
  rightShoulder: "upperarm_r",
  rightElbow: "lowerarm_r",
  rightWrist: "hand_r",
  rightThumb1: "thumb_01_r",
  rightThumb2: "thumb_02_r",
  rightThumb3: "thumb_03_r",
  rightIndex1: "index_01_r",
  rightIndex2: "index_02_r",
  rightIndex3: "index_03_r",
  rightMiddle1: "middle_01_r",
  rightMiddle2: "middle_02_r",
  rightMiddle3: "middle_03_r",
  rightRing1: "ring_01_r",
  rightRing2: "ring_02_r",
  rightRing3: "ring_03_r",
  rightPinky1: "pinky_01_r",
  rightPinky2: "pinky_02_r",
  rightPinky3: "pinky_03_r",
  leftHip: "thigh_l",
  leftKnee: "calf_l",
  leftAnkle: "foot_l",
  leftToe: "ball_l",
  rightHip: "thigh_r",
  rightKnee: "calf_r",
  rightAnkle: "foot_r",
  rightToe: "ball_r",
}

export const DIRECTOR_UNIVERSAL_MANNEQUIN_JOINT_NODE_MAP: Partial<Record<DirectorMannequinJoint, number>> = {
  pelvis: 64,
  spine: 53,
  spineMiddle: 52,
  chest: 51,
  neck: 2,
  head: 1,
  leftClavicle: 26,
  leftShoulder: 25,
  leftElbow: 24,
  leftWrist: 23,
  leftThumb1: 22,
  leftThumb2: 21,
  leftThumb3: 20,
  leftIndex1: 6,
  leftIndex2: 5,
  leftIndex3: 4,
  leftMiddle1: 10,
  leftMiddle2: 9,
  leftMiddle3: 8,
  leftRing1: 18,
  leftRing2: 17,
  leftRing3: 16,
  leftPinky1: 14,
  leftPinky2: 13,
  leftPinky3: 12,
  rightClavicle: 50,
  rightShoulder: 49,
  rightElbow: 48,
  rightWrist: 47,
  rightThumb1: 46,
  rightThumb2: 45,
  rightThumb3: 44,
  rightIndex1: 30,
  rightIndex2: 29,
  rightIndex3: 28,
  rightMiddle1: 34,
  rightMiddle2: 33,
  rightMiddle3: 32,
  rightRing1: 42,
  rightRing2: 41,
  rightRing3: 40,
  rightPinky1: 38,
  rightPinky2: 37,
  rightPinky3: 36,
  leftHip: 58,
  leftKnee: 57,
  leftAnkle: 56,
  leftToe: 55,
  rightHip: 63,
  rightKnee: 62,
  rightAnkle: 61,
  rightToe: 60,
}

export interface DirectorUniversalMajorJoint {
  id: DirectorMannequinJoint
  label: string
  group: "头与身体" | "左手臂" | "右手臂" | "左腿脚" | "右腿脚"
}

export const DIRECTOR_UNIVERSAL_MAJOR_JOINTS: DirectorUniversalMajorJoint[] = [
  { id: "head", label: "头", group: "头与身体" },
  { id: "neck", label: "颈部", group: "头与身体" },
  { id: "chest", label: "上身", group: "头与身体" },
  { id: "spineMiddle", label: "胸椎", group: "头与身体" },
  { id: "spine", label: "腰部", group: "头与身体" },
  { id: "pelvis", label: "骨盆", group: "头与身体" },
  { id: "leftShoulder", label: "左肩", group: "左手臂" },
  { id: "leftElbow", label: "左肘", group: "左手臂" },
  { id: "leftWrist", label: "左手 / 手腕", group: "左手臂" },
  { id: "rightShoulder", label: "右肩", group: "右手臂" },
  { id: "rightElbow", label: "右肘", group: "右手臂" },
  { id: "rightWrist", label: "右手 / 手腕", group: "右手臂" },
  { id: "leftHip", label: "左髋", group: "左腿脚" },
  { id: "leftKnee", label: "左膝", group: "左腿脚" },
  { id: "leftAnkle", label: "左脚踝", group: "左腿脚" },
  { id: "leftToe", label: "左脚", group: "左腿脚" },
  { id: "rightHip", label: "右髋", group: "右腿脚" },
  { id: "rightKnee", label: "右膝", group: "右腿脚" },
  { id: "rightAnkle", label: "右脚踝", group: "右腿脚" },
  { id: "rightToe", label: "右脚", group: "右腿脚" },
]
